# Generated by Django 3.2.6 on 2021-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(default='None', max_length=2),
        ),
    ]
