# Generated by Django 3.2.6 on 2021-08-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Groupss',
        ),
    ]
