# Generated by Django 3.2.6 on 2021-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='None', max_length=255)),
                ('author', models.CharField(default='None', max_length=36)),
                ('description', models.CharField(default='None', max_length=255)),
            ],
            options={
                'db_table': 'Groupss',
            },
        ),
    ]
