# Generated by Django 3.2.6 on 2021-08-30 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
